USE [master]
GO

/****** Object:  Database [GTISoftware]    Script Date: 09/03/2024 16:15:41 ******/
CREATE DATABASE [GTISoftware]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GTISoftware', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GTISoftware.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GTISoftware_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GTISoftware_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GTISoftware].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GTISoftware] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GTISoftware] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GTISoftware] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GTISoftware] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GTISoftware] SET ARITHABORT OFF 
GO

ALTER DATABASE [GTISoftware] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GTISoftware] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GTISoftware] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GTISoftware] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GTISoftware] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GTISoftware] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GTISoftware] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GTISoftware] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GTISoftware] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GTISoftware] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GTISoftware] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GTISoftware] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GTISoftware] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GTISoftware] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GTISoftware] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GTISoftware] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GTISoftware] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GTISoftware] SET RECOVERY FULL 
GO

ALTER DATABASE [GTISoftware] SET  MULTI_USER 
GO

ALTER DATABASE [GTISoftware] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GTISoftware] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GTISoftware] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GTISoftware] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GTISoftware] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GTISoftware] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GTISoftware] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GTISoftware] SET  READ_WRITE 
GO


